# Generated by Django 3.2 on 2021-01-28 03:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210126_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
