# Generated by Django 3.2 on 2021-01-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210128_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(),
        ),
    ]
