# Generated by Django 3.2 on 2021-01-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210128_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
